services:
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - "23000:80"
    volumes:
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: [ nginx-debug, '-g', 'daemon off;' ] # Runs nginx in debug mode
  nextjs:
    build:
      context: .
      dockerfile: nextjs.dockerfile
    container_name: nextjs
