name: NextJSApp

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install deps
        run: npm ci

      - name: Building
        run: npm run build:cloudflare

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./.open-next

  # tba testing

  deploycloudflare:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output 
          path: ./.open-next
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with: 
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}
